server.port: 8081
server.servlet.context-path: /authorization-service
application:
  jwt:
    public-key: ${API_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjZ6M55QHMHHoI4Dmdqy6qBDVuq+Bd2g3SC3lLQVg/EKjN7pqs/g2bDk3LL7ynKa5ilntwAVNw/Oqk4kdjciVcPb5gsLEt4RSwH8OxH99XxNJc01Ruxf0uh9FA4bMlXYd9LgSEkWHegK32QRkEM3iEid6NJttkakgW99N9e0uXqX8xC4kHYPuhDMqcw/yh+NPO2DMm6XCWPK0lgfRWkHKKe1+lehtDo6KLcQHGZu5YaQtvfRW2QaA4D1pflMEL6TmM4mgrOIlTykFKNaauGTeQAbeenswXkV/REqO0iX2/BAv7DXclQxvs2QEsLogj6AHDypVe21iQS4nKuv9iLeMCQIDAQAB}
    private-key: ${API_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNnoznlAcwcegjgOZ2rLqoENW6r4F3aDdILeUtBWD8QqM3umqz+DZsOTcsvvKcprmKWe3ABU3D86qTiR2NyJVw9vmCwsS3hFLAfw7Ef31fE0lzTVG7F/S6H0UDhsyVdh30uBISRYd6ArfZBGQQzeISJ3o0m22RqSBb30317S5epfzELiQdg+6EMypzD/KH4087YMybpcJY8rSWB9FaQcop7X6V6G0OjootxAcZm7lhpC299FbZBoDgPWl+UwQvpOYziaCs4iVPKQUo1pq4ZN5ABt56ezBeRX9ESo7SJfb8EC/sNdyVDG+zZASwuiCPoAcPKlV7bWJBLicq6/2It4wJAgMBAAECggEALAP4RU2TwnHUtZwthPsAdJXu57v+oC8q52skTI7causHMZ3l5hOiTpal2GlsnFWRWzfCFilP1zRXcs1t+xA5qkeImySP4X3l/mA/JcF+JNuou4ZvfZfffy2S1JrD4Tw56UKAk1860SghHfkoZLSoq/3LFKiuMFSBcyx/XY0fGVlEr1sxeSUNoQCvpnvzY9A2PMco5STqd+PnEF4zlpT0Wi4NStt96yFI8N1PWrtUqO0pb4RsZTawyD+R+f0pH4QNg9VIt+oM8M9npxE0/EwJB3HijY8tSYWod+zeFW1Ibbqdf27+3bzgk75+InaDbhXQbyCZA0hGJJz1a5p7nhL71QKBgQDTBLc8F/SsmsOPVgGRFVoAdNlk3SVsZqpO30rfBN28zyKZS+SRMURfAc3u+owuOuOcWzh9txsJAoO9XsLxz0BN7O+VIUJezG+Cs378YKhK1S7IbhqEhM1l9udgpCGd9ZkpYHkmMa8zNXwFcWbnkAmQFvVhXmgMwSdkwKa1umi8BwKBgQCrzrlEpP38RW49h3Z/HHMjDRgLE1nenVSJ6Bb4/BzXj7lx9xflLqDGT4na1rKMEMxG35MdsjaZubNcPvGS5vUj7ySJ8MM+lpPzQ4yUdTVm0dQNQfV6z/5TksWTeZ9G2gLOKibvNkKtCBESOcyuqolGNLwIsFpwn58ScRvg2nqTbwKBgHfDBmexxOitUW4pRuxbrN/zcWpgZJv4TJJFAo4+icZd3OoZ+5g32PD+6izGwAaA36tezlnzMQHVDoXMoWFx2bIgVf1SigOZjXQlgV2lUf5erZWNf7lUUeqbzce4f2fR+uJT4Y4+xouOwFuqd9fWlMbVcOCZHv6WJVB2Umdza3vDAoGAaq+b7DxoW1bh9eNAef44oPNokrgZfltEO76bRVGIt3LQPSyq8e3aeEq71+CqTr+/meMLf81CioL+FbIgYJB6eS3vCpkvJJZsmQrBKQ7/cjGp8/GZdgHidBMYDVPgzCZkx5D1TGXtUXVI5IBv0aakR6xHdz3La1Qze0gxf5crtpECgYEA0tGXewwTkQ8wOwWkL5Fc86Vjmano4cWggKDPxlLUm1Qwy7fvgbfYYhP08P8R3TFtcD0j26vVgZwedT4SnReL9WlCnhgFbaCj1L6mpIm7asvLoG5QnLyRGhuxAY9VewFrJpu9Wsuflz8RSSbESRdNSr05dHLVNaG8zzDBuSxZlNQ=}
    expiration-ms: 86400000
    issuer: http://ilham.web.id/
spring:
  messages.basename: i18n/messages
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:inventory}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 60000
      minimum-idle: 30
      max-lifetime: 3600000
      maximum-pool-size: 30
      initialization-fail-timeout: 1
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    root: DEBUG