server.port: 8082
server.servlet.context-path: /inventory-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ilham.web.id/
          jwk-set-uri: http://localhost:8081/login-service/api/auth/token/jwks.json
  messages.basename: i18n/messages
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

http-conn-pool:
  max-total: 20
  default-max-per-route: 20
  max-per-routes:
    - scheme: http
      host: localhost
      port: 8081
      max-per-route: 20

neutrino:
  url: https://neutrinoapi.net/convert
  connection-request-timeout: 10000
  connect-timeout: 10000
  read-timeout: 10000
  api-key: ${N_API_KEY}
  user-id: ${N_USER_ID}

logging:
  level:
    root: DEBUG